// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtcnosxbkzxeojnhidiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y25vc3hia3p4ZW9qbmhpZGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NzA1MDUsImV4cCI6MjA3NzA0NjUwNX0.4Gvq27KPeDOXzNmVF6i9MR0CeJB0t2Kdc2lGcMuXjdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});